# 新加入角色可自行添加
ElysianRealmConfig: 
  人之律者: 
    - 人律乐土
    - 爱律乐土
  空之律者: 
    - 空律乐土
    - 女王乐土
  格蕾修: 
    - 繁星乐土
    - 格蕾修乐土
    - 绘世乐土
  阿波尼亚: 
    - 阿波尼亚乐土
    - 戒律乐土
  伊甸: 
    - 伊甸乐土
    - 黄金乐土
  帕朵菲莉丝: 
    - 帕朵乐土
    - 猫猫乐土
    - 菲利丝乐土
  缭乱星棘: 
    - 火塔乐土
    - 烤箱乐土
    - 星棘乐土
    - 星塔乐土
  天元骑英: 
    - 天元乐土
    - 泥头鹅乐土
  次生银翼: 
    - 大鸭鸭乐土
    - 次生银翼乐土
  卡萝尔: 
    - 卡萝尔乐土
  梅比乌斯: 
    - 梅比乌斯乐土
    - 蛇蛇乐土
  渡鸦: 
    - 渡鸦乐土
  雷之律者: 
    - 雷律乐土
  雷律平A流: 
    - 雷律平A流
  雷律天罚流: 
    - 雷律天罚流
  失落迷迭: 
    - 迷迭乐土
  狂热蓝调Δ: 
    - 萝莎莉娅乐土
    - 粉毛乐土
    - 德尔塔乐土
  不灭星锚: 
    - 星锚乐土
    - 星猫乐土
  爱莉希雅: 
    - 爱莉乐土
    - 爱莉希雅乐土
  薪炎之律者: 
    - 炎律乐土
    - 薪炎乐土
  识之律者: 
    - 识律乐土
    - 识宝乐土
  魇夜星渊: 
    - 奶希乐土
    - 冰希乐土
  菲谢尔: 
    - 皇女乐土
    - 菲谢尔乐土
  彼岸双生: 
    - 双生乐土
    - 黑希乐土
  辉骑士 · 月魄: 
    - 幽兰戴尔乐土
    - 月魄乐土
    - 呆鹅乐土
  暮光骑士 · 月煌: 
    - 月煌乐土
    - 紫苑乐土
  圣仪装 · 今样: 
    - 今样乐土
    - 卡莲乐土
    - a卡乐土
    - A卡乐土
  御神装 · 勿忘: 
    - 勿忘乐土
    - 机八乐土
    - 冰八乐土
    - 八重樱乐土
  苍骑士 · 月魂: 
    - 月魂乐土
    - 冰箱乐土
    - 冰塔乐土
  破晓强袭: 
    - 强袭乐土
  月下初拥: 
    - 月下乐土
  理之律者: 
    - 理律乐土
    - 摩托鸭乐土
    - 车车乐土
  女武神 · 荣光: 
    - 荣光乐土
  人律蓄力流: 
    - 人律蓄力流
    - 人律纯蓄流
    - 人律蓄力
  李素裳: 
    - 李素裳乐土
    - 月痕乐土
  维尔薇: 
    - 维尔薇乐土
    - 维尔微乐土
    - v2v乐土
  女王大招流: 
    - 女王大招流
    - 空律大招流
  真红骑士 · 月蚀: 
    - 姬子乐土
    - 真红乐土
    - 月蚀乐土
  时帆旅人: 
    - 包菜乐土
    - 爱酱乐土
    - 爱衣乐土
  真理之律者: 
    - 真律乐土
    - 真鸭乐土
    - 真理之律者乐土
  第六夜想曲: 
    - 第六夜想曲乐土
    - 冰卡乐土
    - s卡乐土
    - S卡乐土
    - 怪盗乐土
